#!/bin/bash
if ! [ "$USER" = root ]; then
  echo run this script with sudo
  exit 3
fi

kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml
kubectl create -f https://docs.projectcalico.org/manifests/custom-resources.yaml