#!/bin/bash
if ! [ "$USER" = root ]; then
  echo run this script with sudo
  exit 3
fi

mkdir -p "$HOME"/.kube
sudo cp -i /etc/kubernetes/admin.conf "$HOME"/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config